<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="nosetests" tests="5" errors="1" failures="1" skip="0"><testcase classname="test_create_issue.TestCreateIssue" name="test_create_issue" time="1.098"><error type="exceptions.AttributeError" message="'str' object has no attribute 'headers'&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): codespace-api.myjetbrains.com&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;POST /youtrack/rest/user/login HTTP/1.1&quot; 200 17&#10;requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): codespace-api.myjetbrains.com&#10;requests.packages.urllib3.connectionpool: DEBUG: &quot;PUT /youtrack/rest/issue HTTP/1.1&quot; 201 0&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------"><![CDATA[  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/s1ider/Projects/test-api/test_create_issue.py", line 15, in test_create_issue
    issue_id = r.headers['location'].split('/')[-1]
'\'str\' object has no attribute \'headers\'\n-------------------- >> begin captured logging << --------------------\nrequests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): codespace-api.myjetbrains.com\nrequests.packages.urllib3.connectionpool: DEBUG: "POST /youtrack/rest/user/login HTTP/1.1" 200 17\nrequests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): codespace-api.myjetbrains.com\nrequests.packages.urllib3.connectionpool: DEBUG: "PUT /youtrack/rest/issue HTTP/1.1" 201 0\n--------------------- >> end captured logging << ---------------------']]></error></testcase><testcase classname="test_delete_issue.TestDeleteIssue" name="test_delete_issue" time="1.277"></testcase><testcase classname="test_delete_issue.TestDeleteIssue" name="test_delete_unexisted_issue" time="0.626"></testcase><testcase classname="test_get_issue.TestGetIssue" name="test_get_issue" time="0.342"></testcase><testcase classname="test_get_issue.TestGetIssue" name="test_get_issue_invalid_id" time="0.332"><failure type="exceptions.AssertionError" message='404 != 403&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): codespace-api.myjetbrains.com&#10;requests.packages.urllib3.connectionpool: DEBUG: "GET /youtrack/rest/issue/ZZZZZZ HTTP/1.1" 404 86&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------'><![CDATA[  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/s1ider/Projects/test-api/test_get_issue.py", line 25, in test_get_issue_invalid_id
    self.assertEquals(r.status_code, 403)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
'404 != 403\n-------------------- >> begin captured logging << --------------------\nrequests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): codespace-api.myjetbrains.com\nrequests.packages.urllib3.connectionpool: DEBUG: "GET /youtrack/rest/issue/ZZZZZZ HTTP/1.1" 404 86\n--------------------- >> end captured logging << ---------------------']]></failure></testcase></testsuite>
